### ISSUE TITLE
installer does not register _natlink_core_.pyd

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#101]
After downloading natlink natlink5.1.0-py3.8-32-setup.exe and executing this file, it seems the admin mode is not activated, although I clicked for it. The inno setup program cannot register _natlink_core.pyd. 

When developing on my other computer all works smooth. Also after download and the warning of potential dangerous software, the admin mode is asked for and the installer runs.

What can be the difference?
![error installing natlink](https://user-images.githubusercontent.com/21167695/165057011-f735d02e-e5fe-4c29-b2c9-4f06ab1a0d3c.png)
![warning from windows](https://user-images.githubusercontent.com/21167695/165057013-0e789cd2-a9fc-4d83-8791-8d717c2e122d.jpg)
![warning potentially dangerous software](https://user-images.githubusercontent.com/21167695/165057017-cf311089-8419-4970-8937-e8bc6fc2c67b.jpg)

**Comment by LexiconCode** [comment]
Make sure you have Microsoft Visual C++ Redistributable when compiling 
See 
https://github.com/dictation-toolbox/natlink/issues/86

Install
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

To test that you have Microsoft Visual C++ Redistributable bake in to the dll.

- note you will need to find the path to dumpbin.exe 

 .'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86\dumpbin.exe' /DEPENDENTS "C:\Program Files (x86)\Natlink\site-packages\natlink\_natlink_core.pyd"

**Comment by LexiconCode** [comment]
Good to close?

**Comment by quintijn** [comment]
is solved and explained in https://github.com/dictation-toolbox/natlink/issues/86
