### ISSUE TITLE
Please put an "activate" Powershell and command  script in C:\Program Files (x86)\Natlink

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#110]
This script should:
- add C:\Program Files (x86)\Python39-32 and C:\Program Files (x86)\Python39-32\Scripts to the shell path.
- add the  Natlink site-packages to the python system environments

So that in the command line the user could now type ".\activate" and get a python in their enviornmet that matches roughly what natlink will have.  useful if the user wants to run a command line python program like natlinkconfigfunctions.py or do some development or diagnostics.

**Comment by quintijn** [comment]
I cannot fully appreciate this enhancement, but... go ahead!

**Comment by dougransom** [comment]
Somebody did the batch file already, and a windows shortcut too.  can live without the powershell version.
