### ISSUE TITLE
Please don't release natlinkconfigfunctions.py as a user interface.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#111]
It has always caused no end of trouble for new natlink users get things working when they have to run a python program.  I had managed to get rid of these in favor of scripts before the switch to natlink light.   It is normal to release a script and not a py file as user interface when proving a command line to a user.  see https://flit.pypa.io/en/latest/pyproject_toml.html for how to do this.

the user can then just run "natlinkconfigfunctions" from a command shell.  no worrying about the right python environment, the script will set that up.

Please update the document https://natlink.readthedocs.io/en/latest/configure.html to read

When running the natlinkconfigfunctions **script**  (soon to be released), next step is automatically performed …

Just wrap the call to natlinkconfigfunctions.py with both a powershell and batch file script.   Or better, use flit or to build the command since it can probably that for you in  a place that will be in the path.  look how that was done in pyproject.toml last fall before natlink light.

**Comment by quintijn** [comment]
Doug, I am sorry, but cannot find in the history of the project these lines. If you can, please isolate them and paste them here.

**Comment by quintijn** [comment]
I now found the branch again, makeflitinstall, I believe. But I cannot find yet how to let flit make the batch file user interface to the natlinkconfigfunctions.py.

**Comment by quintijn** [comment]
Has been done now, I think?

**Comment by quintijn** [comment]
So close!!
