### ISSUE TITLE
Python for all users weirdness with pip

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#117]
If Python is installed for all users, pip installs packages to platformlib if and only if pip running with admin privileges.

i.e.

`PS C:\Users\Doug\OneDrive\doug\dication_toolbox\natlink_merge\natlink\src\natlinkcore> pye_platlib.exe
C:\Program Files (x86)\Python39-32\Lib\site-packages
PS C:\Users\Doug\OneDrive\doug\dication_toolbox\natlink_merge\natlink\src\natlinkcore>
`
If pip is running with user privilege's, packages like unimacro are installed to 
`C:\Users\Doug\AppData\Roaming\Python\Python39\site-packages\`

Users who install Python for all users must be aware of this and configure natlink accordingly.

**Comment by dougransom** [comment]
A possible solution is to something like this when an install folder is required:

`>>> import unimacro as u
>>> u
<module 'unimacro' from 'C:\\Users\\Doug\\AppData\\Roaming\\Python\\Python39\\site-packages\\unimacro\\__init__.py'>
>>> u.__file__
'C:\\Users\\Doug\\AppData\\Roaming\\Python\\Python39\\site-packages\\unimacro\\__init__.py'
>>>
`

**Comment by quintijn** [comment]
This is a pity. It means, that if we want to upgrade python packages, it should always be done in an elevated natlinkconfig...

**Comment by LexiconCode** [comment]
done in https://github.com/dictation-toolbox/natlink/pull/121
