### ISSUE TITLE
natlinkcore should be removed from natlink

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#119]
The more I work on natlinkcore, the more i think it should be in a seperate repository from natlink.

It seems unwieldy to have two packages (natlink and natlinkcore) which usually :
- released at seperate times/commits.
- use different tags to mark releases
- use a different build system (Cmake and innno setup vs pytest & flit).
- may be branched separately

**Comment by quintijn** [comment]
OK, I take your opinions serious, so go ahead!

**Comment by dougransom** [comment]
@LexiconCode i am happy to do it once https://github.com/dictation-toolbox/natlink/pull/121 is integrated and any changes @quintijn has for https://github.com/dougransom/natlink/tree/umt_july22 have been pulled to DT:master as well so we can have a working unicode asap- that is the most important thing to me, since everything else works.  I would prefer to cut a release that works with unimacro before doing the changes for [this issue](https://github.com/dictation-toolbox/natlink/issues/119) so we can get something working on peoples desk. There might not be any changes to natlinkcore for unimacro but we don't know yet.

I don't  think [this issue](https://github.com/dictation-toolbox/natlink/issues/119) it is urgent, just important.  It just can be confusing to work on.  We can cut a release at any time of natlinkcore or natlink the way it is now.  

We should endevour to keep the master of natlink and natlinkcore releasable at any time and do so frequently (like about monthly if there are any changes).

**Comment by dougransom** [comment]
PR Submitted https://github.com/dictation-toolbox/natlink/pull/122.  PR should be approved same time as https://github.com/dougransom/natlinkcore copied/forked into dictation toolbox.

**Comment by dougransom** [comment]
done, see https://github.com/dictation-toolbox/natlinkcore
