### ISSUE TITLE
Powershell to allow users to enter Natlink python environment

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#138]
While there are many ways to go about this having a single place to enter into Natlink python environment to manage packages will simplify the experience.

The trick here is when the installer builds is it creates this file to the correct Python environment. That way when the user installs Natlink it always has the correct Python path.

Ideally it would be nice to use visualized python environments but that is not possible at this time.

**Comment by quintijn** [comment]
Hi LexiconCode, I cannot judge on this. We should discuss this further, or with Doug Ransom.

**Comment by LexiconCode** [comment]
The issue is Python can be off or on path. As we provide documentation this can be a challenge as the documentation is a bit different per environment. The point is we don't when I leave this up to the end user having to figure out this process will when we can provide a clear path that works. So instead of reconciling these differences in the documentation provide one method for both scenarios. This could be very simple. 

`cd C:\Program Files (x86)\Python310-32` into the Natlink Python environment wherever that path may be.

That way any command like `python` eg ('python -m pip install package') will work as expected.

There's a few ways one we could create bat file during the installer install phase or we could create another config or figure out how to add it to a natlink ini config stored in .natlink

Once that's accomplished the documentation can be as go to "natlink_environment.bat" and manage any python packages

**Comment by LexiconCode** [comment]
done in https://github.com/dictation-toolbox/natlink/commit/f30fb8ee06615752e3c2434552c3c7856e32c966
