### ISSUE TITLE
Config failed on brand new install

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#144]
Configured directories for unimacro, dragonfly, vocola2 during the install — first time attempting to install natlink on this machine.

Settings didn't take.  this was the resulting natlink.ini

PS C:\Users\doug> cat .\.natlink\natlink.ini
[directories]

[settings]
log_level = INFO
load_on_startup = True
load_on_begin_utterance = False
load_on_mic_on = True
load_on_user_changed = True

[manual configuration]
instruction1 = set next line in the directories section when you
instruction2 = want to define a Natlink user directory, independent of
instruction3 = any package, like Dragonfly, Unimacro or Vocola.
instruction4 = Note: you can drop a python grammar file in any of the directories,
instruction5 = the distinction is made for package updates, and for convenience
natlinkuserdirectory = ~\Documents\UserDirectory

[vocola]
vocolatakesunimacroactions = True

**Comment by dougransom** [comment]
Running  natlinkconfig_gui  same behvior.

**Comment by dougransom** [comment]
Here is the version info:


```
PS C:\Users\doug> pip list
Package       Version
------------- -------
debugpy       1.6.3
dtactions     1.5.6
natlink       5.4.4
natlinkcore   5.3.4
pip           22.3.1
pydebugstring 1.0.0.0
pyenvutils    1.0.0.3
PySimpleGUI   4.60.4
pywin32       305
setuptools    63.2.0
unimacro      4.1.2
vocola2       3.1.3
```

**Comment by LexiconCode** [comment]
Does the CLI have the same issue?

**Comment by dougransom** [comment]
Unknown.  I reran the GUI after install and it worked. So maybe it was user error?

**Comment by dougransom** [comment]
I am going to close it for now.
