### ISSUE TITLE
natlink uses a different python version

### ISSUE THREAD

**Issue by tripfish** [dictation-toolbox/natlink#147]
When I start DNS, the natlink window shows Python version 3.10.3. But my installed Python version is 3.10.8. I saw that there is a Python310.dll in the natlink program directory (c:\Program Files (x86)\Natlink\site-packages\natlink\). This has the version 3.10.3. Why is this dll used? Where does this come from? Isn't the global Python (3.10.8) installation used?

DNS 15.3
natlink 5.4.4 (installed with the last installer)
Windows 10

**Comment by quintijn** [comment]
I guess this should not bother us, I close the issue.

**Comment by LexiconCode** [comment]
> I guess this should not bother us, I close the issue.

This is something I'm actually working on and it comes from the pyd being statically compiled and then installed on a different subversion of python.
