### ISSUE TITLE
Publishing and Loading Grammars - Documentation Improvements

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#149]
The directories section of natlink have a list of directories which are less special (more general) than I thought. They are just directories natlink loads a bunch of python files.

I would like to add some docs to natlink.readthedocs which describes the load process, and how one can publish a grammar (whether unimacro or plain natlink and possibly dragonfly) by creating a python package, and just adding the python package name to natlink.ini.  

I think this would make life easier for those who want to share grammars and use grammars published in github or pypi.

**Comment by quintijn** [comment]
Please do so! And also: users can create their own natlinkuserdirectory /'usergrammarsdirectory (find a nice name for this). "natlinkuserdirectory" nearly clashes with "natlink_userdir"  (also a possible env variable, see https://natlink.readthedocs.io/en/latest/configure.html) pointing to the directory where natlink.ini is located.


We could also

**Comment by quintijn** [comment]
Let us close this, and come back to it later if necessary!
