### ISSUE TITLE
get setTrayIcon working again

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#152]
This was a not very much used function of natlink. Especially when things were moving, often in "exclusive mode", (in unimacro grammar _repeat and in the originalsamplegrammars _mous.py), a (changing) tray icon could be shown, in order to give the user feedback about the state of the grammar.

This function does not work any more with the python3 release.

1. The icons are gone, they are put back, for the moment in Doug and mine unimacro fork, in the folder defaulticons. Moreover also custom icons could be used, see icons directory also in unimacro fork.

2. How can we then use this feature again? 

See some remarks in testNatlinktime.py in the tests area of the same unimacro fork directory.

**Comment by drmfinlay** [comment]
I'm not sure about the changes to Unimacro, but setTrayIcon() should be fixable by reverting some of the changes made in commit 5dd0784.  Would you like me to fix this, @quintijn?

**Comment by quintijn** [comment]
Dane, please go ahead. I think putting the .ico files in the correct directory should be sufficient...

(not unimacro though, although only there it is used...)

**Comment by drmfinlay** [comment]
Okay then, I'll have a go at fixing this.  The icons probably just need to be bundled into the PYD as resources, like the message window is.
