### ISSUE TITLE
Natlink freezes DNS15 mic

### ISSUE THREAD

**Issue by F5lx6k564f3** [dictation-toolbox/natlink#153]
Every time Python executes an example script DNS15 mic freezes. Natlink correctly tracks clicks i.e. on the DNS mic icon but audio signals are blocked somehow. If I cancel the example script process, the spoken words are recognized afterwards and DNS works correctly. What could be the reason for this? 

Natlink message window is in debug modus and gives me no hint except: "Warning, no directories specified for Natlink grammars, falling back to default configuration". Python version is 3.11 (32-bit).

**Comment by LexiconCode** [comment]
@F5lx6k564f3 Python 3.11 hasn't been tested as we just added compiling support. Does this issue occur with python 3.10?

**Comment by dougransom** [comment]
Ugh.  I have been thinking when it comes to actually having a stable release we should upgrade to the latest python at that time, for now there are so many things we are working on I don't really want to jump to python 3.11 yet, especially now I now it appears broken. I enjoy working on python a lot more than C++ and installers!

**Comment by F5lx6k564f3** [comment]
Don't worry, it doesn't seem to be a problem with the Python version. I tried it with 3.10, but without success. I even reinstalled DNS15 and Natlink. No change. What else can I do to track down the problem?

**Comment by dougransom** [comment]
Well, lets see if that particular example script causes problems on others install.

 Can you post a link to to the exact script you are running (or paste it here if it is not on github)?

**Comment by F5lx6k564f3** [comment]
I must correct my statement. It has something to do with the Python version. I used Dragonfly (the standard example script) without paying attention to the fact that this is only supported by Natlink with Python 2. Is there then a way to write Python macros through Natlink without installing Python 2? On https://qh.antenna.nl/ it says that even Unimacro and Vocola are not supported. I don't want to run Python 3 scripts via the subprocess module or via multiprocess module (the two ways I know to use both Python 2 and Python 3 at the same time).

**Comment by F5lx6k564f3** [comment]
Thank you! Now I finally had the time to carefully reinstall all of it. And it works. I have no idea why. Maybe the user rights, since I had installed it first from a user account and then through the administrator account...
