### ISSUE TITLE
Natlink also recognising a python version that is not installed for all users

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#16]
When installing python, you have the choice "install for all users" or "install for current user". These are two different cases for the place where Python does its registry settings.

all users:  HKLM (HiveKeyLocalMachine)

only you: HKCU (HiveKeyCurrentUser).

When registering Natlink (natlink.pyd), a registry setting is made in the appropriate python area, but up to now only for the all users case.

The config program already tries to distinguish the two cases (this is done in getRegistryPythonPathDict in natlinkstatus.py (around line 520). This is however not fully tested.

Question for the natlink.pyd developers, to build this also in the C++ code where the path for natlinkmain.py is collected.

**Comment by dougransom** [comment]
in the makeflitinstall branch the current natlinkconfig_cli and natlink seem to work regardless of python is installed for all users or just the current user.  i am currently running a python installed just for me.
