### ISSUE TITLE
Install error: "nsapps.ini not found in that directory"

### ISSUE THREAD

**Issue by 77capr** [dictation-toolbox/natlink#165]
Hi, thanks for providing this software!

I recently switched to Dragon Professional 16 and trying to install NatLink, I am getting the following error:

![dnsInstallError](https://github.com/dictation-toolbox/natlink/assets/11540283/5d99e5ac-4b52-4668-8fed-02b503608d14)

Any ideas on how to get around it?

Choosing a different installation directory does not change the error. Restarting the computer also does not help.

Windows 11
Microsoft Surface Pro 8
DNS 16 Professional

**Comment by LexiconCode** [comment]
Greetings! When I have a moment in the next 24 hours I will drop a binary for you here that supports DNS 16. It's already in the master branch but not released.

**Comment by LexiconCode** [comment]
[natlink5.5.4-py3.10-32-setup.zip](https://github.com/dictation-toolbox/natlink/files/11994137/natlink5.5.4-py3.10-32-setup.zip)

**Comment by 77capr** [comment]
Thanks very much! That worked. I appreciate the extra effort!
