### ISSUE TITLE
DPI 16: Deactivating one rule of a grammar can deactivate all the rules of that grammar

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#179]
mdbridge (Mark)
"There is a Dragon bug where deactivating one rule of a grammar can deactivate all the rules of that grammar.
 I have worked around this in Vocola 2.9 by first determining if any deactivation's are needed, and if so deactivating all  rules in that case before doing any activations. I expect this bug also affects dragonfly."

**Comment by quintijn** [comment]
This should be examined with some pytest test scripts in either https://github.com/dictation-toolbox/natlink/tree/master/pythonsrc/tests or in https://github.com/dictation-toolbox/natlinkcore/tree/main/tests (this latter directory seems preferable to me).

**Comment by quintijn** [comment]
And I should study markdown...

**Comment by quintijn** [comment]
I made good progress to solving this issue, in a way, that the code also works for Dragon 15 (and therefore probably back to 13). 

I will do a few more testing, and then make a new version of natlinkcore. (a pip install --upgrade natlinkcore will do)

**Comment by quintijn** [comment]
Succes seems to be there!!!

I am about to accept my own PR into the natlinkcore repository...

**Comment by quintijn** [comment]
All committed to natlinkcore, new pip release natlinkcore 5.3.8

**Comment by quintijn** [comment]
I think we can safely close this issue as solved!!!
