### ISSUE TITLE
Playback/mimic can crash DPI v16

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#180]
On DPI 16: Playback/mimic can crash DPI.  The problem does not occur  v15, v14, v13. I will provide more details.

**Comment by drmfinlay** [comment]
I think we discovered this problem months ago, didn't we?  Sorry I didn't open an issue then.  If I recall correctly, most of Dragonfly's test suite fails with v16 because of this problem.

**Comment by quintijn** [comment]
Also here, please somebody isolate the issue with a pytest test script...

**Comment by quintijn** [comment]
In natlinkcore, directory src/natlinkcore/SampleMacros/ there is an interactive test grammar _sample_runmimic.py.

This one does a natlink.recognitionMimic allright, also with Dragon 16. 

Please try this grammar!!!

We will need an example where it goes wrong, before we can tackle this issue

**Comment by quintijn** [comment]
I think, I can safely close this issue...
