### ISSUE TITLE
Location of  natlink files, like natlink.ini

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#187]
I think we would be smart to use [platformdirs] https://pypi.org/project/platformdirs/ to locate files for natlink, such as config files etc.   

We good also to have a way to locate this folder from a grammar or package like natlink, that would also work if the same package were running under talon or some other system (if we can decouple unimacro from natlink for example).

**Comment by quintijn** [comment]
Please elaborate, but I cannot grasp the implications right now...

**Comment by quintijn** [comment]
platformdirs is now in the dependencies list of natlinkcore. For the config purposes it is not used, as it only "~" (\users\username\)  is needed, or a directory specified with env variable NATLINK_SETTINGSDIR which should hold a ".natlink" directory.

But platformdirs can be used in other places.
