### ISSUE TITLE
documentation (one page on readthedocs) does not upload

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#189]
I try to make a one page documentation on natlink.readthedocs.io. It is uploaded in the main branch, but  this job is not run automatic any more. Probably disabled when LexiconCode made his .md documentation for github.io site.

I want to keep this as a one page site on natlink.readthedocs.io.

Can the running of this job be repaired?

Thanks, Dane of Aaron...

**Comment by drmfinlay** [comment]
I think this is now working again.  If not, please let me know.  Sorry, again, that it took me a while to fix!

**Comment by quintijn** [comment]
Hi Dane, I made changes and did a PR to natlink. Should my changes be uploaded to natlink.readthedocs.io now automatically instantly, or at least after a short while?

Sorry for this, but I understand little of the mechanism. I had to restore the 3 helper files, Makefile, conf.py and make.bat, maybe this reverted a change you made?

**Comment by drmfinlay** [comment]
Hi Quintijn, I can see that your PR triggered a documentation build, so that part is working.  Unfortunately, the build failed because a newly-required RTD configuration file is missing.  I'll add it to the natlink master branch shortly.  You will need to do a "git pull" afterward.

**Comment by drmfinlay** [comment]
All right, I have got it working for you now using the one-page sphinx 'documentation' folder.
https://natlink.readthedocs.io

**Comment by quintijn** [comment]
Thanks! Quintijn
