### ISSUE TITLE
No module named 'natlink' -  kb100 Fork

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#20]
@kb100 Upon starting Dragon
```
Natlink Version: 4.2
Python Version: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
An exception occurred loading 'natlink' module
NatLink: an exception occurred in 'natlink.redirect_all_output_to_natlink_window'.
Error message:
No module named 'natlink'
NatLink: an exception occurred in 'natlink.run_loader'.
Error message:
No module named 'natlink'
```
`.natlink`
`C:\Users\Main`
```
[directories]
my_scripts=D:\Backup\Library\Documents\Caster

[settings]
log_level=INFO
```

**Comment by kb100** [comment]
You wouldn't happen to have the dictation-toolbox fork of natlink somehow in your path would you? If you could, try running `import natlink` from a python script run from python 3.8 and let me know the output.

**Comment by LexiconCode** [comment]
It does not appear to be on path nor can I find it with it Windows path variable without DPI running.

[Running] python -u "C:\Users\Main\AppData\Local\Temp\tempCodeRunnerFile.python"
Traceback (most recent call last):
  File "C:\Users\Main\AppData\Local\Temp\tempCodeRunnerFile.python", line 1, in <module>
    import natlink
ModuleNotFoundError: No module named 'natlink'

if DPI is running I can import natlink from any Python script.
```
d:\Backup\Library\Documents\Caster
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\python38.zip
C:\Program Files (x86)\Natlink\site-packages
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\DLLs
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib
C:\Users\Main\AppData\Local\Programs\Python\Python38-32
C:\Users\Main\AppData\Roaming\Python\Python38\site-packages
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages
c:\users\main\desktop\pyia2-py3-support
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32\lib
C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Pythonwin
```

A reasonable guess would be that natlink is not being added to the path early enough in the startup natlink initialization?

**Comment by LexiconCode** [comment]
Interestingly enough I can run NatLink out of process using Waitforspeech python subsystem

**Comment by kb100** [comment]
Given the paths you posted, im guessing you didnt install python 3.8 for all users? I definitely assumed the registry key for python lives in the global location. If you are willing, try reinstalling python for all users to confirm this fixes the issue. In the mean time i will think about where the registry key will be for a user specific install

**Comment by LexiconCode** [comment]
> Given the paths you posted, im guessing you didnt install python 3.8 for all users? I definitely assumed the registry key for python lives in the global location. If you are willing, try reinstalling python for all users to confirm this fixes the issue.

Sure, I'll have feedback shortly.

**Comment by LexiconCode** [comment]
> If you are willing, try reinstalling python for all users to confirm this fixes the issue. In the mean time i will think about where the registry key will be for a user specific install

Unfortunately there's no change with the issue. I verified that is indeed installing as all users.

![image](https://user-images.githubusercontent.com/24551569/91922205-fb141880-ec92-11ea-87aa-315f2ea03d23.png)

I also went ahead uninstalled all other Python versions 2.7.18(32-bit), 3.8.3 (64-bit). Restart the PC (You never know). Then installed Natlink.

**Comment by kb100** [comment]
`Root: HKLM; Subkey: "Software\Python\PythonCore\{#PythonVersion}\PythonPath\{#MyAppName}"; ValueType: string; ValueData: "{#SitePackagesDir}"; Flags: uninsdeletekey`

This is the line i use in the installer to add the natlink module to the python path. Can you check your registry and see if the key exists and if anything looks out of place?

**Comment by LexiconCode** [comment]
Not sure how that exactly translates the following keys but here's what I have.

`Computer\HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.8-32\PythonPath`
![image](https://user-images.githubusercontent.com/24551569/91923626-6ca19600-ec96-11ea-9b0c-3a31b88f4372.png)

Computer\HKEY_USERS\S-1-5-21-2213828637-2599326268-2025979009-1001\SOFTWARE\Python\PythonCore\3.8-32\PythonPath

![image](https://user-images.githubusercontent.com/24551569/91923537-306e3580-ec96-11ea-84e2-714a6ab8600a.png)


`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.8-32\PythonPath\Natlink`

![image](https://user-images.githubusercontent.com/24551569/91923445-01f05a80-ec96-11ea-92a1-45064394c4cb.png)

**Comment by LexiconCode** [comment]
modifying `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.8-32\PythonPath` from `none` to

`C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\;C:\Users\Main\AppData\Local\Programs\Python\Python38-32\DLLs\` seems to have resolved error.

**Comment by LexiconCode** [comment]
If the config and underlying loader could accept Windows variables in a path.
`my_scripts=%%HOMEPATH%%\Documents\Caster`

**Comment by kb100** [comment]
Were those screen shots taken before or after you installed for all users? HKLM is where things installed for all users go, whereas HKCU is just for the current user. The HKEY_USERS entry is just a copy of the HKCU entry, or rather HKEY_USERS holds the HKCU entries for all users, and the HKCU is just a shortcut to the HKEY_USERS entry for the currently logged in user.

That's why it's strange that your HKLM entry is empty except for what the natlink installer created. Perhaps installing for the current user then all users results in a different registry footprint than directly installing for all users. I guess the natlink installer could just put entries in both HKLM and HKCU.

Just FYI, the way we are adding to the pythonpath is not by modifying the PythonPath key as you did, as this may be difficult to undo on uninstall since the user could arbitrarily change this. Instead, we create the Subkey PythonPath/Natlink whose value has the natlink site packages directory.  See https://stackoverflow.com/questions/897792/where-is-pythons-sys-path-initialized-from point 6 about subkeys.

**Comment by LexiconCode** [comment]
> 
> Were those screen shots taken before or after you installed for all users? 

I am very confident installed Python with its default settings which include all users. To answer your question specifically yes those screenshots are before I attempted to reinstall.

**Comment by LexiconCode** [comment]
Issue Sale - closing
