### ISSUE TITLE
Configure Natlink (for Vocola) errors (can't make `natlink_settings\vocolagrammars`)

### ISSUE THREAD

**Issue by sboosali** [dictation-toolbox/natlink#216]
After doing `v` in "Configure Natlink via CLI" and choosing an existing directory:

```
==== Please specify the wanted directory in Dialog window ====

Set in section "vocola", option "VocolaUserDirectory" to "C:\Users\sboosali\Documents\Natlink\Vocola"
Set option "vocoladirectory" to "vocola2"
cannot create directory, 1 level above should exist: "natlink_settings"
Cannot set "vocolagrammarsdirectory", the given path is invalid: "natlink_settings\vocolagrammars"
copied "Unimacro.vch" from "C:\Program Files (x86)\Python310-32\lib\site-packages\dtactions\Vocola_compatibility" to "C:\Users\sboosali\Documents\Natlink\Vocola"
```

Also, "Configure Natlink via GUI" has no option for vocola like it does for a unimacro (I don't know if that's related or an intentional).

I installed Natlink 5.5.7, to the default directories in the wizard, then pip installed Vocola2. (I also tried configuring with admin, and tried creating the subdirectory of the error message in random locations, but I don't know where and it didn't work.) Thanks.

**Comment by sboosali** [comment]
and `natlink.ini`:

```
[directories]
userdirectory = C:\Users\sboosali\Documents\Natlink

[autohotkey]
ahkuserdir = C:\Users\sboosali\Documents\AutoHotkey
ahkexedir = C:\Users\sboosali\AppData\Local\Programs\AutoHotkey\v2

[settings]
log_level = INFO
load_on_startup = True
load_on_begin_utterance = False
load_on_mic_on = True
load_on_user_changed = True

[settings.debugadapterprotocol]
dap_enabled = False
dap_port = 7474
dap_wait_for_debugger_attach_on_startup = True

[previous settings]
vocolauserdirectory = ~\Documents\Natlink\Vocola
```

**Comment by quintijn** [comment]
Hi sboosali, I will delve into this ASAP

**Comment by sboosali** [comment]
thank you! (I've used Natlink for years, but with my own shim. Now on a new computer I've decided to try out Vocola 2, and hope to be able to help out more the next time there's an issue.)

I don't know if it's a simple "use a `create_subdirs` optional argument", or some less wider issue from my computer's specific configuration of different versions of Windows/Dragon/Natlink/Vocola/etc.

**Comment by sboosali** [comment]
(I opened this issue in a bit of a rush, since I'd been working on it for a few hours before giving up as my wrists started hurrying, so apologies if I missed any relevant filepath/version details, which I can provide today of course).

I'd tried GitHub searching for keywords like "natlink_settings" to no avail, and followed the Vocola 2 instructions modified, as they seem to recommended the older installation directory. Thanks again.

https://vocola.net/v2/InstallVocola

**Comment by quintijn** [comment]
Hi sboosali, 

We are doing a lot of things concurrently. When we make a new release for Natlink, including also Vocola, we will check the config procedure once more.

Hope you can manage with the pyhon 2.7 release for the moment.

I now close this issue, please make a new one if later  you still have problems with configuring Vocola.

Greetings, Quintijn

**Comment by sboosali** [comment]
sounds good and no worries. (I've just been copy-pasting and find-replacing some Vocola scripts I found for Emacs off Google into Dragonfly rules.)
