### ISSUE TITLE
Error messages could ease troubleshooting: Natlink Key.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#22]
"Failed to find Natlink key in Windows registry.
Failed to extract value from Natlink key."

Someone setting up a dev environment or a user troubleshooting an install need more information.

Maybe display the  registry key?
Maybe display "Workaround:  add this folder natlink/.../... to Pythonpath".

Also should we be modifying a python key or should we have a Natlink key off Computer\HKEY_LOCAL_MACHINE\SOFTWARE\?  Might that just eliminate the problem altogether?  Especially if you upgrade your python or something.

**Comment by reckoner** [comment]
My advice is to create a `Natlink.pth` file in your `site-packages` directory and avoid using the registry altogether. The `Natlink.pth` contains the names of the directories where you want to find your natlink files and the `natlink.pyd`.
