### ISSUE TITLE
sys.argv not recognised in natlink.pyd

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#3]

**Comment by quintijn** [comment]
LexiconCode @LexiconCode apr. 20 13:07
I've been recently reminded that Natlink utilizes a embedded interpreter, there is the potential for AttributeError: 'module' object has no attribute 'argv' this is an issue all the way up to Python 3.7 and fixed in Python 3.8. https://bugs.python.org/issue32573

import sys
print(sys.argv)
which could be fixed by

import sys

if not hasattr(sys, 'argv'):
    sys.argv  = ['']

Dane Finlay @Danesprite apr. 20 13:28
The way to fix this in C++ is to call the PySys_SetArgvEx() C-Python function with updatepath = 0 after calling Py_Initialize() in CDgnAppSupport::Register()

**Comment by Danesprite** [comment]
Thanks for opening this @quintijn! I'll open a pull request with my proposed C++ fix.
