### ISSUE TITLE
getWave() not working with Python 3

### ISSUE THREAD

**Issue by wolfmanstout** [dictation-toolbox/natlink#30]
I get a UnicodeDecodeError raised when I call getWave() in Python 3 (tested on 3.7 and 3.8). I'm using this grammar:
https://github.com/dwks/dragonfly-save-audio/blob/master/_natlink_save_audio.py

And I get this exception: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 29: invalid start byte

I've never built NatLink so I haven't tested this, but my hypothesis is that the bug is here:
https://github.com/dictation-toolbox/natlink/blob/b62327460c062161d0599affd4d976836da236e2/NatlinkSource/ResultObject.cpp#L313

It looks like this should be y# instead of s#: https://docs.python.org/3/c-api/arg.html#strings-and-buffers

**Comment by LexiconCode** [comment]
I can reproduce this. I'll see if I can try to compile with your suggested fix.

**Comment by LexiconCode** [comment]
Okay your suggested fix works. Simply replace with the following file in `MacroSystem\core\PYD` then reregister Natlink.

Once I figure out how to run the tests on natlink I'll see about getting it upstream.


[natlink_3.8_Ver15.zip](https://github.com/dictation-toolbox/natlink/files/5978760/natlink_3.8_Ver15.zip)

**Comment by wolfmanstout** [comment]
Awesome, thank you for fixing this! Confirmed that this works for me and resolves my last remaining Python 3 issue.
