### ISSUE TITLE
Document Natlink compiling instructions

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#31]
The project has been stalled a number of times due to difficulties compiling Natlink and it is frequently asked question for those of which to contribute.  Having some documentation thoroughly documenting the compiling would be to the benefit of the project.

**Comment by dougransom** [comment]
I have documented how to build natlink with Visual Studio thanks to Jonas' help.  it is slightly cumbersome, but workable.   there is a readme.md and visual studio project file.

**Comment by LexiconCode** [comment]
That's great to hear. We can continue to refine the process as we go along. I'll close this once there is a PR/commit merged.

**Comment by dougransom** [comment]
the visual studio project kept self destructing.   

I ended up re-running the wizard t update to the latest ATL.    it seems to be robust.  also set up so you shouldn't have to change any compiler/project settings to build (ie. location of of Python include files is set via environment variables).  so far so good.  The branch is makeflitinstall.  still need to update instructions.

I won't mark this done until someone else has successfully built it and we merge to the mainline. I think we are close to something stable (i think the binary is stable).

**Comment by LexiconCode** [comment]
The PIP install works great on my system and I have a few others testing. However I will wait for more instructions for compiling and set up as I imagine it's a bit different than what's currently on the readme.

**Comment by dougransom** [comment]
Yes, I'll update the instructions and then see if you can follow them.  Maybe I'll get to it on the weekend.
