### ISSUE TITLE
natlink_3.8_ANSI / natlink2_3.8_UNICODE are missing

### ISSUE THREAD

**Issue by codebold** [dictation-toolbox/natlink#38]
Natlink libraries natlink_3.8_ANSI / natlink2_3.8_UNICODE are not available. 

Are there any plans to provide those libraries in the future or how can those libraries be generated?

Thanks for your help!

**Comment by quintijn** [comment]
No, this is not planned. The "ANSI" versions were for Dragon version up to 11. 
From version 12 upward, the "UNICODE" versions were used. 
All for python 2.x, the latest versions only for python 2.7

So when now all development is being done for python 3 (3.7, 3.8), these naming conventions are obsolete.

In the current development, new names are chosen, should be better documented than is now.
