### ISSUE TITLE
Double loading grammars

### ISSUE THREAD

**Issue by tripfish** [dictation-toolbox/natlink#44]
When I start Dragon, the grammar files are loaded correctly. When I activate the microphone (with wake up or npadd) the grammars files are reloaded.

I saved the log for this. [https://pastebin.com/MZ5gNmn2](https://pastebin.com/MZ5gNmn2)
On lines 26-30 you can see that when Natlink starts _main and _xmlrpc-nb-server are loaded. From line 87 you can see that I have activated the microphone and that the two files are reloaded, although they have not been changed.

German Windows 10
Dragon 15.3 with german Profil
Python 3.8

**Comment by LexiconCode** [comment]
I can confirm this. My Recognition Observer such as `on begin` and so forth are being registered twice.

**Comment by quintijn** [comment]
I know, I will solve this after the new natlinkmain is running. We first need a good compiled natlink.pyd...

**Comment by LexiconCode** [comment]
> 
> 
> I can confirm this. My Recognition Observer such as `on begin` and so forth are being registered twice which are contained in caster entry point grammar `_caster.py`.

I don't experience this issue with 5.0.0 Natlink via PIP

**Comment by tripfish** [comment]
Yes, I can confirm that too. Thanks for the info.
