### ISSUE TITLE
No module named 'natlinkmain' error

### ISSUE THREAD

**Issue by maxxiimo** [dictation-toolbox/natlink#45]
Hello, 

Recently, I've had to reinstall the operating system on my machine. In the process I upgraded my DNS from 13 to 15 and in reconfiguring my voice recognition environment the following Natlink message now appears on DNS start:

```
Failed to find Natlink key in Windows registry.
Failed to extract value from Natlink key.
An exception occurred loading 'natlinkmain' module
Error message:
No module named 'natlinkmain'
```

--

My DNS version: 15.61.200.010
My OS specifications:

Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎12/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

--

To troubleshoot I have:

1. Reinstall Python and Natlink several times to ensure that I'm installing correctly (per the instructions):

Python 3.8.8 (32-bit), all users, at C:\Python38-32

I also cleared system of all Python and Natlink remnants and restart operating system with each reinstall.

Everything I attempted was always with administrative privileges.

2. Add additional path variables in the following order:

```
C:\Python38-32\Lib\site-packages\natlinkcore\
C:\Python38-32\Lib\site-packages\
C:\Python38-32\Scripts\
C:\Python38-32\
```

3. Add the following registry entry:

![added registry entry](https://user-images.githubusercontent.com/54768/112891282-f5a27380-90a5-11eb-9dd6-ba2eb0aa9cb7.png)

This last effort produced this Natlink message:

```
An exception occurred loading 'natlinkmain' module
Error message:
no module named 'natlinkmain'
```

4. Attempt to import natlinkmain:

![import attempt](https://user-images.githubusercontent.com/54768/112891403-208cc780-90a6-11eb-8a2e-0d3e051497d2.png)

Line 113:

![line 113](https://user-images.githubusercontent.com/54768/112891480-300c1080-90a6-11eb-9eca-5a2ec9ac9757.png)

--

Additional information...

I did notice that on the first configuration of Natlink I would receive the following error message:

![error message](https://user-images.githubusercontent.com/54768/112891559-46b26780-90a6-11eb-9a56-cd5419d0297f.jpg)

The message in .natlink\configurenatlink_error.txt:

```
Traceback (most recent call last):
  File "c:\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\configurenatlink.pyw", line 1355, in <module>
    app = MyApp(True)
  File "C:\python38-32\lib\site-packages\wx\core.py", line 2137, in __init__
    self._BootstrapApp()
SystemExit: OnInit returned false, exiting...
```

The settings in natlinkstatus.ini:

```
[usersettings]

NatlinkPydOrigin = C:\Python38-32\Lib\site-packages\natlinkcore\PYD\natlink_3.8_Ver15.pyd
```

--

At this point I am out of ideas, and am wondering if you have come across this error message before, is it a known issue or maybe a new issue, or is there something that I am doing in my troubleshooting steps incorrectly? Thank you.

**Comment by maxxiimo** [comment]
NOTE: I used the following discussion to try to resolve...

https://github.com/dictation-toolbox/natlink/issues/20

**Comment by maxxiimo** [comment]
Okay, issue resolved for me but possible installation issue still remains for others. How I resolved...

My registry entry was pointing to the file `natlinkmain.py` which got me past the initial Natlink error message, and to the second error message. The solution was to point the registry entry to the folder: `C:\Python38-32\Lib\site-packages\natlinkcore`, rather than just the file.

A user on [stackoverflow ](https://stackoverflow.com/questions/66876756/registry-and-module-error-installing-natlink-python-38-on-windows-10) pointed this out to me, and also mentioned:

"I've been getting the same exact error as you and this is what finally fixed it for me today. I wonder if this was a bug introduced by a recent change, since I imagine Natlink is supposed to do this automatically."

**Comment by michaelscheung** [comment]
> A user on [stackoverflow ](https://stackoverflow.com/questions/66876756/registry-and-module-error-installing-natlink-python-38-on-windows-10) pointed this out to me, and also mentioned:
> 
> "I've been getting the same exact error as you and this is what finally fixed it for me today. I wonder if this was a bug introduced by a recent change, since I imagine Natlink is supposed to do this automatically."

Ha that was me ;) I also got the same OnInit returned false error as you. My own issue was that I wasn't using the WOW6432Node, hence I mistakenly thought that was your issue as well.

Natlink correctly identifies the NatlinkCore path as seen in the image below, it just fails to write it to the registry editor and hence we have to do it manually. There should be a way to do it automatically.

![image](https://user-images.githubusercontent.com/3878375/113605315-54627280-95fb-11eb-866c-3fd6435a07cb.png)

I actually switched over to the Python 3 implementation after days of being unable to get the Python 2 version to work. Nevertheless, I am grateful that these tools exist as it has been critical in allowing me to use my computer despite my disability.

**Comment by maxxiimo** [comment]
Ha, no kidding. Well, thank you. Same with me, absolutely critical for programming – which is challenging when you can't use a mouse or keyboard. This weekend I almost threw in the towel thinking that I would have to re-create all of my macros in DNS or Knowbrainer. Neither have the versatility and capabilities of the Natlink and Dragonfly combo. So, I'm really thankful for the direction as well as the tool for sure!

**Comment by quintijn** [comment]
Effort is done to get a new natlink.pyd file compiled, for which the registry settings are not needed any more. 

When you need the python 3 version of natlink now, please pip uninstall natlinkcore, and follow the instructions on https://qh.antenna.nl/unimacro/installation/installationexperimentalversionpython3.html

Hope the new version is going to be up and running soon!!

**Comment by quintijn** [comment]
We are now close and probably solved things by now. It is not sure whether we leave the registry setting, or let natlink.pyd import like
from natlinkcore import natlink
etc.

**Comment by LexiconCode** [comment]
I believe this is been resolved right @quintijn?

**Comment by fusentasticus** [comment]
Then also plz delete last two lines of ...\natlink\check_com_registration.ps1 or perhaps replace with ` Get-Command python` if Path lookup is the new canonical way of finding Python.

**Comment by LexiconCode** [comment]
There's a new proposed solution in https://github.com/dictation-toolbox/natlink/issues/69

**Comment by quintijn** [comment]
#69 is another issue, the correct python version being on the system path, so natlink.pyd can start a python interpreter.

Instead of "import natlink", we need now "from natlinkcore import natlink", so qualified imports all the time. This may still be wrong at some points.

This issue is closed, when you run into this again, please open a new issue.

**Comment by quintijn** [comment]
The question of fusentatsticus remains: Doug, can you look into this?

Then also plz delete last two lines of ...\natlink\check_com_registration.ps1 or perhaps replace with Get-Command python if Path lookup is the new canonical way of finding Python.

**Comment by dougransom** [comment]
I will eventually fixup or replace check_com_registrations to something that gives a diagnostic on natlink setup (location of config files, maybe post their contents, dragon registry settings, which python is in the path, etc).  For now @fusentasticus can you please delete the last two lines of the script and submit it - I don't have a dev environment conveniently available and spending much of my free time on other hobbies lately.

**Comment by quintijn** [comment]
natlinkmain has now gone, with the new pre release: c:\python38-32\python.exe -m pip install --upgrade pip

the python file that does the loading of the grammars, and handles callbacks (microphone on/off and user speech profile switching) is not loader.py.

References to natlinkmain.py should be fixed in the different packages.
