### ISSUE TITLE
also shot

### ISSUE THREAD

**Issue by maxxiimo** [dictation-toolbox/natlink#46]
Hello, 

Recently, I've had to reinstall the operating system on my machine. In the process I upgraded my DNS from 13 to 15 and in reconfiguring my voice recognition environment the following Natlink message now appears on DNS start:

Failed to find Natlink key in Windows registry.
Failed to extract value from Natlink key.
An exception occurred loading 'natlinkmain' module
Error message:
No module named 'natlinkmain'

--

My DNS version: 15.61.200.010
My OS specifications:

Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎12/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

--

To troubleshoot I have:

1. Reinstall Python and Natlink several times to ensure that I'm installing correctly (per the instructions):

Python 3.8.8 (32-bit), all users, at C:\Python38-32

I also cleared system of all Python and Natlink remnants and restart operating system with each reinstall.

2. Add additional path variables in the following order:

C:\Python38-32\Lib\site-packages\natlinkcore\
C:\Python38-32\Lib\site-packages\
C:\Python38-32\Scripts\
C:\Python38-32\

3. Add the following registry entry:

![added registry entry](https://user-images.githubusercontent.com/54768/112891282-f5a27380-90a5-11eb-9dd6-ba2eb0aa9cb7.png)

This last effort produced this Natlink message:

An exception occurred loading 'natlinkmain' module
Error message:
no module named 'natlinkmain'

4. Attempt to import natlinkmain:

![import attempt](https://user-images.githubusercontent.com/54768/112891403-208cc780-90a6-11eb-8a2e-0d3e051497d2.png)

Line 113:

![line 113](https://user-images.githubusercontent.com/54768/112891480-300c1080-90a6-11eb-9eca-5a2ec9ac9757.png)

Additional information...

I did notice that on the first configuration of Natlink I would receive the following error message:

![error message](https://user-images.githubusercontent.com/54768/112891559-46b26780-90a6-11eb-9a56-cd5419d0297f.jpg)

Everything I attempted was always with administrative privileges.

The message in .natlink\configurenatlink_error.txt:

Traceback (most recent call last):
  File "c:\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\configurenatlink.pyw", line 1355, in <module>
    app = MyApp(True)
  File "C:\python38-32\lib\site-packages\wx\core.py", line 2137, in __init__
    self._BootstrapApp()
SystemExit: OnInit returned false, exiting...

The settings in natlinkstatus.ini:

[usersettings]

NatlinkPydOrigin = C:\Python38-32\Lib\site-packages\natlinkcore\PYD\natlink_3.8_Ver15.pyd

--

At this point I am out of ideas, and am wondering if you have come across this error message before, is it a known issue or maybe a new issue, or is there something that I am doing in my troubleshooting steps incorrectly? Any help is greatly appreciated, as a developer who cannot use his hands, Natlink in combination with Dragonfly is a godsend. Seriously. Thank you.

Chris

**Comment by bijanbina** [comment]
Same here on windows 7

**Comment by LexiconCode** [comment]
For now Chris I been utilizingthis working commit https://github.com/dictation-toolbox/natlink/tree/43dd2ccce52ab181b9dac81268ddd6dc447a745b until some of these issues have been worked out.

**Comment by quintijn** [comment]
natlink can now also be installed with pip... Instructions follow...

**Comment by LexiconCode** [comment]
Closing this is been resolved utilizing the pip package PIP
