### ISSUE TITLE
Fail to lunch start_natlinkconfig.exe

### ISSUE THREAD

**Issue by bijanbina** [dictation-toolbox/natlink#47]
On Windows 7, Python 3.8.10 lunching `start_natlinkconfig.exe` fail with following error:
Any help?

```
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\natlinkcore\ConfigureNatlink\configurenatlink.pyw", line 1355, in <module>
    app = MyApp(True)
  File "C:\python38\lib\site-packages\wx\core.py", line 2137, in __init__
    self._BootstrapApp()
SystemExit: OnInit returned false, exiting...
```

**Comment by LexiconCode** [comment]
For now I'm utilizing this working commit https://github.com/dictation-toolbox/natlink/tree/43dd2ccce52ab181b9dac81268ddd6dc447a745b

**Comment by bijanbina** [comment]
@LexiconCode Thanks for your help.

I built the specified version that you mentioned with flit and install it. Now following error pops up

```netlinkconfigfunctions failed because of fatal error:
netlinkconfigfunctions configCheckNatlinkPydFile: wantedPydPath does not exits:
C:\Python38\Lib\site-packages\natlinkpy\MacroSystem\core\PYD\natlink_3.8_ANSI.pyd
```

So sad I couldn't get this working :( Don't know what to do. I copy a similar file there and again last error shows up.

Hope to see Natlink works again soon

**Comment by LexiconCode** [comment]
> @LexiconCode Thanks for your help.
> 
> I built the specified version that you mentioned with flit and install it. Now following error pops up
> 
> ```netlinkconfigfunctions failed because of fatal error:
> netlinkconfigfunctions configCheckNatlinkPydFile: wantedPydPath does not exits:
> C:\Python38\Lib\site-packages\natlinkpy\MacroSystem\core\PYD\natlink_3.8_ANSI.pyd
> ```
> 
> So sad I couldn't get this working :( Don't know what to do. I copy a similar file there and again last error shows up.
> 


To make sure we're on the same page is the file actually there?

**Comment by quintijn** [comment]
now pip install natlink should work, and you get version 5.0.0

configure with natlinkconfig_cli. 

natlinkconfig_cli.exe is a program that is in the Scripts directory of the 38-32 python version.

**Comment by dougransom** [comment]
fixed now
