### ISSUE TITLE
  There is also a small typo in the install command for upgrading pip, an additional backtick "`" at the end: in pip install --upgrade pip`

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#49]
from https://github.com/dictation-toolbox/natlink/issues/48 
`There is also a small typo in the install command for upgrading pip, an additional backtick "`" at the end: in pip install --upgrade pip` 
`
so it doesn't get overlooked.

**Comment by LexiconCode** [comment]
Fixed in https://github.com/dictation-toolbox/natlink/pull/51
