### ISSUE TITLE
recognitionMimic fails with several grammar rules

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#5]

**Comment by quintijn** [comment]
unittestNatlink.py fails for example in test:   def testRecognitionMimicCommands(self): 
around line 1154. 
I now uncommented only this test.

The mimic simply fails, but after a few tries, also the message below pops up in the Messages window:

 testCommandRecognition(['mimic', 'three', 'painting'], shouldWork=1, testGram=testGram)  

The first two lines pass:
      testCommandRecognition(['hello', 'world'], shouldWork=0, testGram=testGram)  
        testCommandRecognition(['mimic', 'runone'], shouldWork=1, testGram=testGram)  

(hello world as dictate, mimic runone is a simple rule, that one works)...










GramClassBase.load(), Error at loading the grammar  (<class 'natlink.NatError'>, NatError('A SRERR_VALUEOUTOFRANGE error occurred calling ISRCentral::GrammarLoad from GrammarObject.cpp 283.'), <traceback object at 0x11F69528>)
Traceback (most recent call last):
  File "C:\NatlinkGIT3\Natlink\MacroSystem\core\natlinkutils.py", line 342, in load
    self.gramObj.load(grammar,allResults,hypothesis)
natlink.NatError: A SRERR_VALUEOUTOFRANGE error occurred calling ISRCentral::GrammarLoad from GrammarObject.cpp 283.
Unexpected error load GramClassBase: (<class 'natlink.NatError'>, NatError('A SRERR_VALUEOUTOFRANGE error occurred calling ISRCentral::GrammarLoad from GrammarObject.cpp 283.'), <traceback object at 0x11F69EE8>)
Traceback (most recent call last):
  File "C:\NatlinkGIT3\Natlink\MacroSystem\core\natlinkutils.py", line 545, in load
    GramClassBase.load(self,gramBin,allResults,hypothesis)
  File "C:\NatlinkGIT3\Natlink\MacroSystem\core\natlinkutils.py", line 342, in load
    self.gramObj.load(grammar,allResults,hypothesis)
natlink.NatError: A SRERR_VALUEOUTOFRANGE error occurred calling ISRCentral::GrammarLoad from GrammarObject.cpp 283.

**Comment by LexiconCode** [comment]
@quintijn is is still an issue?

**Comment by quintijn** [comment]
I think so, keep it open

**Comment by quintijn** [comment]
I made some improvements in several files, that can bring people who want to analyze this closer to a solution. I think it is in the C++ code of recognitionMimic itself, as the grammars run in "normal" mode fine.

1. checkout branch mimicProblem.
2. Interactively: copy the file _sample_runmimic.py from SampleMacros into for example your UserDirectory.
3. after toggle microphone, say the commands that are to be read in the file: "mimic runzero" or "mimic north" etc. 

That's the interactive way.

Now try to run (interactive session) gramparser.py (from natlinkcore). The compiled grammar is printed via the doctest mechanism.

Then try unittestNatlink (from "PyTest" subdirectory of natlinkcore).
When running only the testRecognitionMimicCommands is executed. Only mimiccs runzero works. The command "mimiccs runone north" already fails.

I think when this is solved, all the list items etc are OK as well. Probably it has to do with some UNICODE or binary issue.

Quintijn

**Comment by LexiconCode** [comment]
Did https://github.com/dictation-toolbox/natlink/pull/124 solve this issue?

**Comment by quintijn** [comment]
Yes, I close
