### ISSUE TITLE
Install Instrution Issues Windows 10

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#50]
From https://github.com/dictation-toolbox/natlink/issues/48

A user might not remember to put the PATH to the python scripts directory on installl.  especially if they use a distriubtion other than the default.

Also, it looks like PIP might have worked on a 64 bit install - natlink should fail to install on a 64 bit python install.  the other packages like unimacro should be fine on any size architecture.

**Comment by quintijn** [comment]
Thanks, try not to forget these instructions...

**Comment by LexiconCode** [comment]
old - re-open on https://github.com/dictation-toolbox/natlink or https://github.com/dictation-toolbox/natlinkcore with info as need.
