### ISSUE TITLE
code cleanup  - redefinition of UNICODE

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#55]
natlinksource has preprocessor definition of UNICODE that is required, and seems to conflict with visual studio.

natlink is never going back to a non-unicode  compile.   the preprocesser defiintion of UNICODE should be removed out of visual studio and the conditional compiled code not required removed from natlinksource.

**Comment by LexiconCode** [comment]
Yes if I remember correctly that convention is only needed for below version 13 of DNS.

**Comment by dougransom** [comment]
I think that perhaps the UNICODE preprocessor command should be renamedif it is to be kept and previous versions of Dragon supported? There is something in Visual Studio includes also called UNICODEthat we are redefining.

**Comment by LexiconCode** [comment]
Yes I could see that logic to have it renamed. It would be good to have previous 13/14 versions supported as the upgrade cost is now 250$. However I know your time/energy is limited so I wouldn't worry about that now. Let me know what you rename it too and how to enable it which might give me a chance to poke and prod.

**Comment by dougransom** [comment]
I'm not going to rename it, just highlighting the issue for the next person who pokes at the code.

**Comment by quintijn** [comment]
Fusentasticus, do you have an opinion about the "#ifdef UNICODE" lines in the .cpp code?

**Comment by dougransom** [comment]
There is some weirdness around unicode, and there were some changes to do with playstring or something that required unicode conversions and using the non-unicode calls to natlink.  Maybe lets just leave this haning around for a while.

**Comment by quintijn** [comment]
Let us leave this for now...
