### ISSUE TITLE
No UserDirectory specified

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#58]
> Quitting the natlinkconfig_cli program allows me to delete natlink.pyd without admin permissions. Next time I start the program it registers successfully. Perhaps it keeps an open file handle while it is running? You can test it by running `r` twice in a row.

> I uninstalled natlink 5.0.0 and installed it again with version 5.1.1. I get the same message in the natlink window saying "no UserDirectory specified".

_Originally posted by @slatesky284 in https://github.com/dictation-toolbox/Caster/issues/907#issuecomment-890576540_

**Comment by dougransom** [comment]
If you delete natlink.pyd,  then rerun natlinkconfig_cli to reregister, it will reinstall natlink.pyd from natlinkcore/PYD.

**Comment by LexiconCode** [comment]
> 
> 
> If you delete natlink.pyd, then rerun natlinkconfig_cli to reregister, it will reinstall natlink.pyd from natlinkcore/PYD.

Thanks for the clarification. According to @slatesky284 the primary issue though is a user directory is not being set.

**Comment by quintijn** [comment]
That should be done via the config program. We will need to add instructions for that.

I think the issue with natlink.pyd being locked is solved with version 5.1.0.

**Comment by LexiconCode** [comment]
> 
> 
> That should be done via the config program. We will need to add instructions for that.
> 
> I think the issue with natlink.pyd being locked is solved with version 5.1.0.

Here is his original message where you can see the commands executed. 
```
C:\Python38-32\Scripts>natlinkconfig_cli
Natlink.dll can not be imported in natlinkstatus
pyd path "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd" does not exist...
no natlink.pyd, clear "NatlinkPydOrigin" setting
copied pyd (=dll) file c:\python38-32\lib\site-packages\natlinkcore\PYD\natlink_3.8_Ver15.pyd to c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd
registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
Natlink is enabled, you can now restart Dragon

Config Natlink> n C:\Users\User\Nextcloud\Software\Dragon\Caster-master
Setting the UserDirectory of Natlink to C:\Users\User\Nextcloud\Software\Dragon\Caster-master

Config Natlink> q
```

However, when I start dragon with natlink it says "no UserDirectory specified". Also, the caster commands are not working.

```
Displaying Python Environment
Warning:
originalPyd setting is missing in natlinkstatus.ini

Warning:
originalPyd setting is missing in natlinkstatus.ini

Cannot find UnimacroDirectory, return ""
Vocola is not installed, no VocolaDirectory
Instructions for attaching a python debugger are in C:\Python38-32\lib\site-packages\natlinkcore\debugging python instructions.docx 
--
-- natlinkmain starting...
Vocola is disabled
Unimacro is disabled
no UserDirectory specified
currentUser at start of Natlink: ('user', 'C:\\ProgramData\\Nuance\\NaturallySpeaking15\\Users\\User\\current')
changeCallback, Type: user, args: ('user', 'C:\\ProgramData\\Nuance\\NaturallySpeaking15\\Users\\User\\current')
setUserInfo, setting language to: enx
no path given for AhkUserDir: ""
natlinkmain started from C:\Python38-32\Lib\site-packages\natlinkcore:
  Natlink version: 5.0.0
  DNS version: 15
  Python version: 38
  Windows Version: 10
----------------------------------------
==============================
natlinkstatus reported the following warnings:

originalPyd setting is missing in natlinkstatus.ini
==============================
```

It seems that the natlinkconfig_cli program thinks it set the user directory, but natlink in dragon does not recognize it.

```
Config Natlink> i
natlinkstatus.getLanguage, Dragon not active, return "enx"
Cannot find UnimacroDirectory, return ""
Vocola is not installed, no VocolaDirectory
---Natlink is enabled
        NatlinkDirectory        c:\python38-32\lib\site-packages\natlinkcore
        InstallVersion  5.0.0
---Vocola is disabled
---Unimacro is disabled
---User defined grammars are enabled
        UserDirectory   C:\Users\User\Nextcloud\Software\Dragon\Caster-master
```

Thinking I made a mistake I tried it again (and rebooted for good measure). I disabled natlink, enabled it and then registered it. If I register a second time then it prints the below error. It also seems to delete the registry key I added at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.8-32\PythonPath\Natlink`. I added the registry key back and I get the same error above about a missing user directory.

```
C:\Python38-32\Scripts>natlinkconfig_cli

Config Natlink> r
do action: (Re) register and enable natlink.pyd
natlinkconfigfunctions failed because of fatal error:

cannot remove natlink.pyd from the core directory: c:\python38-32\lib\site-packages\natlinkcore
Probably Dragon is running

So if Dragon is running, close it.

Then try, if you choose to do so, to Re-register Natlink with this program
(option "r" in the CLI, Command Line Interface).


*** See also the messageBox, and close it

Config Natlink> q
```

Any ideas on what might be going on?

**Comment by LexiconCode** [comment]
I will follow up with them just to verify more time to try to manually set the user directory. I don't think it's an issue of a lack of clear instructions.

**Comment by slatesky284** [comment]
Yep I manually set the user directory and got the same result.

```
c:\Python38-32\Scripts>natlinkconfig_cli.exe

Config Natlink> n
also enter a valid folder

Config Natlink> n C:\Users\User\Downloads\Caster-master\Caster-master
Setting the UserDirectory of Natlink to C:\Users\User\Downloads\Caster-master\Caster-master

Config Natlink> q
```

What exactly is this changing on my system? I could check to see if its correctly applied, so we can see if the problem is in writing or reading this value.

**Comment by LexiconCode** [comment]
> What exactly is this changing on my system? I could check to see if its correctly applied, so we can see if the problem is in writing or reading this value.

in `C:\Users\Your-User\.natlink` look for `natlinkstatus.ini`

**Comment by slatesky284** [comment]
Ahh well that explains it! I had no idea it was changing a file in my user directory. I don't run Windows in an administrator account for security. When I run `natlinkconfig_cli` with my user account it gives an error:

```
c:\Python38-32\Scripts>natlinkconfig_cli.exe
------------------------------------------------------------
originalPyd setting is missing in natlinkstatus.ini

Most often, you solve this by running the
ConfigureNatlink program and Re-register natlink.pyd
(Or run the Command Line Interface with option "r").
start_configurenatlink or start_natlinkconfigfunctions in directory "C:\Python38-32\Scripts".
============================================================
no valid "NatlinkPydOrigin" setting, remove natlink.pyd
You need to run this program in elevated mode. ("NatlinkPydOrigin" setting not valid, natlink.pyd should be removed

(please also close Dragon if it is running)).
Traceback (most recent call last):
  File "C:\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Python38-32\Scripts\natlinkconfig_cli.exe\__main__.py", line 7, in <module>
  File "C:\Python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 2029, in main
    cli = CLI()
  File "C:\Python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 1361, in __init__
    self.config.configCheckNatlinkPydFile()
  File "C:\Python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 263, in configCheckNatlinkPydFile
    raise ElevationError(mess)
natlinkcore.ConfigureNatlink.natlinkconfigfunctions.ElevationError: "NatlinkPydOrigin" setting not valid, natlink.pyd should be removed
```

So I restarted and ran with an admin account. However, this changes the file in the wrong user directory. I manually copied `natlinkstatus.ini` from the admin directory to my user directory and that fixed it. 

I suspect that other users will want this to work for non-admin user accounts. Theoretically, I should be able to create `natlinkstatus.ini` in my own user directory. If it needs to delete `natlink.pyd` for some reason and this requires admin, it'd be more clear if the program handled the exception and printed an info message telling me to manually delete it.

**Comment by LexiconCode** [comment]
Interesting so `natlinkstatus.ini` this being saves the wrong user profile. That strange as elevating the command prompt to administrator shouldn't change the user variable. However it might be provisioned differently with policies set by your organization. If this was a permission issue usually that's fixed by running as administrator temporarily.

**Comment by slatesky284** [comment]
I just have a regular Windows install with a non-admin user as my primary account, and a separate administrator account. When I run Command Prompt from the start menu it says

```
C:\Users\User>echo %username%
User
```

When I right click Command Prompt and then click Run as Administrator it says

```
C:\WINDOWS\system32>echo %username%
Admin
```

I believe only administrator user accounts can run with administrator privilege?

**Comment by quintijn** [comment]
Hi Slateski,

When you run the command prompt (windows start menu, type cmd), you should be able to choose "Run as administrator", you get admin rights, but remain the same "User".

Good question though, where to put the config files:

1. Dragon is always globally installed, I think
2. Python is preferably installed "for all users", but only for one user should also work fine.
3. And then the configuring of Natlink (and possibly other related packages) is only for one user. That does not make sense.

What happens when you switch user, natlink is enabled (via a .ini file in the natlink are og programdata), but the config files of natlink are not accessible because of above strategy. We should investigate this, and make our choices.

Thanks for raising this issue

**Comment by dougransom** [comment]
Registering natlink is always going to require admin privileges because of COM registration.  i would think the config  utility would probably work in  a non-admin account;  if not, this is such an edge case I think the documentation on how to edit the .ini file should be sufficient.  Realistically, if someone has admin privileges, they can assign those to  the account running natlink.  
Completely reasonable given the nature of the product. 

We should probably put in the requirements in the readme.md that the natlink user needs admin privileges.

**Comment by slatesky284** [comment]
> When you run the command prompt (windows start menu, type cmd), you should be able to choose "Run as administrator", you get admin rights, but remain the same "User".

When I open the start menu, type cmd, then right click "Command Prompt" and select "Run as administrator" it opens a terminal. I then type `echo %username%` and it prints "Admin". I don't see any way to retain the same username "User". If you haven't already, you can test this by creating a real non-admin user account and logging into the desktop using it. Let me know the steps if you find a way. Its important to use a real non-admin user account because the UX for elevating an admin user is different.

> if someone has admin privileges, they can assign those to the account running natlink.

I have no problem running the natlinkconfig_cli with an elevated admin account. I'd prefer not to run dragon with an elevated account just because of a config file.

I suspect we got around this in Natlink 4.2 because we had an installer program that knew the current user who is running the installer, but it also asked them to elevate privileges at runtime? With the new pip package we lose the UAC prompt.

I looked for a way to do this with Python and came across this potential solution https://stackoverflow.com/questions/19672352/how-to-run-script-with-elevated-privilege-on-windows. Basically, if the current user is not an admin store the `%username%`, then elevate to admin to configure natlink, but store `natlinkstatus.ini` in the original user's directory.

**Comment by quintijn** [comment]
I released natlinkcore 5.1.2, in which you can give an environment variable DICTATIONTOOLBOXUSER pointing to a directory in which the folder .natlink (among others) can be located. In my case C:\Users\User\Documents\.dictationtoolbox

Please try to uninstall natlink, pip install natlink and run natlinkconfig_cli (possibly natlinkconfig give a problem) and then do a "r" re-register.

**Comment by slatesky284** [comment]
@quintijn Thanks I had a chance to test this out, but it doesn't seem to be working. Am I using it correctly? I set the environment variable at the system level so it'd be the same for Admin and User accounts. I also deleted the old status file.

```
c:\Python38-32\Scripts>echo %DICTATIONTOOLBOXUSER%
C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig
c:\Python38-32\Scripts>del C:\Users\Admin\.natlink\natlinkstatus.ini
```

I installed natlink 5.1.2 and registered again

```
c:\Python38-32\Scripts>natlinkconfig_cli.exe

Config Natlink> r
do action: (Re) register and enable natlink.pyd
no natlink.pyd, clear "NatlinkPydOrigin" setting
copied pyd (=dll) file c:\python38-32\lib\site-packages\natlinkcore\PYD\natlink_3.8_Ver15.pyd to c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd
registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
Natlink is enabled, you can now restart Dragon
registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
Natlink is enabled, you can now restart Dragon
```

It adds a `.natlink` directory but it is empty

```
c:\Python38-32\Scripts>dir C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig

 Directory of C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig

08/08/2021  03:37 PM    <DIR>          .
08/08/2021  03:37 PM    <DIR>          ..
08/08/2021  03:37 PM    <DIR>          .natlink
               0 File(s)              0 bytes

c:\Python38-32\Scripts>dir C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig\.natlink

 Directory of C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig\.natlink

08/08/2021  03:37 PM    <DIR>          .
08/08/2021  03:37 PM    <DIR>          ..
               0 File(s)              0 bytes
```

It did add the natlink status file in my user directory, which I did not expect

```
c:\Python38-32\Scripts>dir C:\Users\Admin\.natlink

 Directory of C:\Users\Admin\.natlink

08/08/2021  03:37 PM    <DIR>          .
08/08/2021  03:37 PM    <DIR>          ..
08/08/2021  03:37 PM               162 natlinkstatus.ini
               2 File(s)            428 bytes
```

Also, the info command returns an error. 

```
c:\Python38-32\Scripts>natlinkconfig_cli.exe

Config Natlink> i
from_config is set, don't try to import natlink, return language: "enx"
Traceback (most recent call last):
  File "c:\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Python38-32\Scripts\natlinkconfig_cli.exe\__main__.py", line 7, in <module>
  File "c:\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 2030, in main
    cli.cmdloop()
  File "c:\python38-32\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "c:\python38-32\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "c:\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 1457, in do_i
    S = self.config.getNatlinkStatusString()
  File "c:\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1928, in getNatlinkStatusString
    D = self.getNatlinkStatusDict()
  File "c:\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1910, in getNatlinkStatusDict
    D[key] = func()
  File "c:\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1353, in getDtactionsDirectory
    return dtactions.getDtactionsDirectory()
AttributeError: module 'dtactions' has no attribute 'getDtactionsDirectory'
```

Is this using the correct package version?
```
c:\Python38-32\Scripts>pip list
Package            Version
------------------ ---------
...
dtactions          1.3.2
natlink            5.1.2
...
```

**Comment by quintijn** [comment]
You are on the right track, I will look through this tomorrow,

Quintijn 

slatesky284 ***@***.***> schreef op 8 augustus 2021 21:47:50 CEST:
***@***.*** Thanks I had a chance to test this out, but it doesn't seem to be working. Am I using it correctly? I set the environment variable at the system level so it'd be the same for Admin and User accounts. I also deleted the old status file.
>
>```
>c:\Python38-32\Scripts>echo %DICTATIONTOOLBOXUSER%
>C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig
>c:\Python38-32\Scripts>del C:\Users\Admin\.natlink\natlinkstatus.ini
>```
>
>I installed natlink 5.1.2 and registered again
>
>```
>c:\Python38-32\Scripts>natlinkconfig_cli.exe
>
>Config Natlink> r
>do action: (Re) register and enable natlink.pyd
>no natlink.pyd, clear "NatlinkPydOrigin" setting
>copied pyd (=dll) file c:\python38-32\lib\site-packages\natlinkcore\PYD\natlink_3.8_Ver15.pyd to c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd
>registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
>registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
>Natlink is enabled, you can now restart Dragon
>registered "c:\python38-32\lib\site-packages\natlinkcore\natlink.pyd"
>Natlink is enabled, you can now restart Dragon
>```
>
>It adds a `.natlink` directory but it is empty
>
>```
>c:\Python38-32\Scripts>dir C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig
>
> Directory of C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig
>
>08/08/2021  03:37 PM    <DIR>          .
>08/08/2021  03:37 PM    <DIR>          ..
>08/08/2021  03:37 PM    <DIR>          .natlink
>               0 File(s)              0 bytes
>
>c:\Python38-32\Scripts>dir C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig\.natlink
>
> Directory of C:\Users\User\Nextcloud\Software\Dragon\Natlinkconfig\.natlink
>
>08/08/2021  03:37 PM    <DIR>          .
>08/08/2021  03:37 PM    <DIR>          ..
>               0 File(s)              0 bytes
>```
>
>It did add the natlink status file in my user directory, which I did not expect
>
>```
>c:\Python38-32\Scripts>dir C:\Users\Admin\.natlink
>
> Directory of C:\Users\Admin\.natlink
>
>08/08/2021  03:37 PM    <DIR>          .
>08/08/2021  03:37 PM    <DIR>          ..
>08/08/2021  03:37 PM               162 natlinkstatus.ini
>               2 File(s)            428 bytes
>```
>
>Also, the info command returns an error. 
>
>```
>c:\Python38-32\Scripts>natlinkconfig_cli.exe
>
>Config Natlink> i
>from_config is set, don't try to import natlink, return language: "enx"
>Traceback (most recent call last):
>  File "c:\python38-32\lib\runpy.py", line 194, in _run_module_as_main
>    return _run_code(code, main_globals, None,
>  File "c:\python38-32\lib\runpy.py", line 87, in _run_code
>    exec(code, run_globals)
>  File "c:\Python38-32\Scripts\natlinkconfig_cli.exe\__main__.py", line 7, in <module>
>  File "c:\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 2030, in main
>    cli.cmdloop()
>  File "c:\python38-32\lib\cmd.py", line 138, in cmdloop
>    stop = self.onecmd(line)
>  File "c:\python38-32\lib\cmd.py", line 217, in onecmd
>    return func(arg)
>  File "c:\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 1457, in do_i
>    S = self.config.getNatlinkStatusString()
>  File "c:\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1928, in getNatlinkStatusString
>    D = self.getNatlinkStatusDict()
>  File "c:\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1910, in getNatlinkStatusDict
>    D[key] = func()
>  File "c:\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1353, in getDtactionsDirectory
>    return dtactions.getDtactionsDirectory()
>AttributeError: module 'dtactions' has no attribute 'getDtactionsDirectory'
>```
>
>Is this using the correct package version?
>```
>c:\Python38-32\Scripts>pip list
>Package            Version
>------------------ ---------
>...
>dtactions          1.3.2
>natlink            5.1.2
>...
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dictation-toolbox/natlink/issues/58#issuecomment-894846022
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by quintijn** [comment]
Please try release 5.1.5, hopefully DICTATIONTOOLBOXUSER now spreads over all modules involved...

**Comment by slatesky284** [comment]
Ok that seems to set the user directory successfully now and its working again!

FYI the status file seems to be missing the `NatlinkPydRegistered = 38;15` line that was present before but maybe that is not required?

I still got the `getDtactionsDirectory` error in the natlink window. This error also displayed if I press `i` in natlinkconfig_cli. I uninstalled dtactions 1.3.2 and upgraded to 1.3.5 and the errors went away. Do you need to update the version dependency for the natlink package? It may have been something wrong in my local install too.

Thanks so much for your help and fast patches! I appreciate it :)

**Comment by dougransom** [comment]
We have not put any effort into versions dependencies for natlink. I am thinking maybe lets do that after we have a release candidate with Vocola, Unimacro, Dragonfly to be working?  it does require us to upgrade the libraries all the time.

@quintijn or @LexiconCode if you want to take this on now might be an idea, but then you will have to keep the version numbers current for dependencies.  If you feel like waiting till you have a release candidate i can try and tweak  pyproject.toml for natlink then.

**Comment by LexiconCode** [comment]
Typically I Freeze dependencies if there's issues. We wouldn't want to freeze dragonfly or anything else like that as they are upgraded frequently.

**Comment by quintijn** [comment]
I can not judge this issue. Can LexiconCode and Doug sort this out?

**Comment by quintijn** [comment]
With the pre release of https://github.com/dictation-toolbox/natlink/releases/tag/natlink5.0.0.pre
the natlink installer (with inno setup) now registers the natlink.pyd file. This seems to work.

We need to add automatic pipping the required packages (vocola2, unimacro, dragonfly2, caster...)

The discussion above can be closed IMHO.
