### ISSUE TITLE
documentation error?

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#59]
in readme.md:

pip install dragonfly (natlink also needs some action modules from dragonfly)

i think that is both wrong, and dragonfly2 is in the pyproject.toml so this step shouldn't be required?

**Comment by LexiconCode** [comment]
it would be `PIP install dragonfly2` as dragonfly points to the old original package.

**Comment by dougransom** [comment]
whiich is already a prereq of the package in pyproject.toml.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LexiconCode** [comment]
hmmm I'm not seeing I'm not seeing dragonfly imported anywhere in Nalink. dtactions has been used in a couple places.

**Comment by quintijn** [comment]
Yeah, but natlink relies on dtactions, so on dragonfly2 too. 

I believe there will be more places where dtactions will use stuff from dragonfly2!!

**Comment by dougransom** [comment]
1.  it needs dragonfly2 not dragonfly, correct?.
2. dragonfly2 is a prereq listed in pyproject.toml so the instruction for the user ti install it with pip is redundant.

**Comment by quintijn** [comment]
Yes, I think so. Can you push the correct readme.md again, Doug?

**Comment by LexiconCode** [comment]
I'm a little confused though for not importing dragonfly anywhere why is it required?

**Comment by dougransom** [comment]
the readme.md is wrong.  code is fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LexiconCode** [comment]
> I believe there will be more places where dtactions will use stuff from dragonfly2!!

I think how the current model works is dragonfly will be depending on dtactions. Right?

**Comment by dougransom** [comment]
i corrected the readme.md.
