### ISSUE TITLE
natlinkcore site package should be added to python path

### ISSUE THREAD

**Issue by MarkRx** [dictation-toolbox/natlink#60]
In order for dragonfly to [import natlink](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_natlink/engine.py#L130) when running the Run_Caster_DNS.bat script it needs to be directly accessible. I think this can be done by putting it on the python path using a module.pth file in the natlink python module.

https://docs.python.org/3/library/site.html

Without the module on the path it fails with this:
> C:\voice\caster>Run_Caster_DNS.bat
> Running DNS/DPI from Dragonfly CLI with Natlink.
> WARNING:engine.natlink:Requested engine 'natlink' is not available: Natlink is not installed: No module named 'natlink' ERROR:command:Requested engine 'natlink' not available.
> Press any key to continue . . .

The path can also manually be modified by setting the PYTHONPATH variable:

> set PYTHONPATH=C:\Python\Python38-32\Lib\site-packages\natlinkcore

**Comment by dougransom** [comment]
I think this is an undesirable solution - think of it as a workaround.

I suspect what is going on is the dependent packages have not been updated since natlink moved to qualified imports.  I think the issue should be reported in caster or other dependent packages.

**Comment by quintijn** [comment]
Well, from the new version of natlink, the import should go different:

from natlinkcore import natlink

Please try, and remove the set PYTHONPATH line above...

**Comment by MarkRx** [comment]
Created https://github.com/dictation-toolbox/dragonfly/issues/354

**Comment by LexiconCode** [comment]
Closing as this is being addressed in dragonfly
