### ISSUE TITLE
ElevationError running natlinkconfig_cli in cmd as administrator

### ISSUE THREAD

**Issue by MarkRx** [dictation-toolbox/natlink#61]
My user is not an admin. Attempting to run natlinkconfig_cli in an elevated CLI yields still the error below.

Temporary workaround: Check "Run this program as an administrator" in the compatibility properties on the natlinkconfig_cli.exe file.

> C:\Users\mrichar2>natlinkconfig_cli
> pyd path "C:\Users\mrichar2\AppData\Roaming\Python\Python38\site-packages\natlinkcore\natlink.pyd" does not exist...
> You need to run this program in elevated mode. (needed for copying the correct natlink.pyd file.
> 
> (please also close Dragon if it is running)).
> Traceback (most recent call last):
>   File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mrichar2\AppData\Roaming\Python\Python38\Scripts\natlinkconfig_cli.exe\__main__.py", line 7, in <module>
>   File "C:\Users\mrichar2\AppData\Roaming\Python\Python38\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 2030, in main
>     cli = CLI()
>   File "C:\Users\mrichar2\AppData\Roaming\Python\Python38\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 1362, in __init__
>     self.config.configCheckNatlinkPydFile()
>   File "C:\Users\mrichar2\AppData\Roaming\Python\Python38\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 281, in configCheckNatlinkPydFile
>     result = self.copyNatlinkPydPythonVersion(wantedPydPath, targetPydPath)
>   File "C:\Users\mrichar2\AppData\Roaming\Python\Python38\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 331, in copyNatlinkPydPythonVersion
>     raise ElevationError("needed for copying the correct natlink.pyd file.")
> natlinkcore.ConfigureNatlink.natlinkconfigfunctions.ElevationError: needed for copying the correct natlink.pyd file.

**Comment by LexiconCode** [comment]
in the future I will try to reproduce this.

**Comment by quintijn** [comment]
I think this problem has been solved, by me. So close!!
