### ISSUE TITLE
VS2019 or VS2022?  ---- natlink.vcxproj issue

### ISSUE THREAD

**Issue by fusentasticus** [dictation-toolbox/natlink#66]
So I'm diving into compiling Natlink for Python 3.8 --- nice instructions in NatlinkSource, but I get bumped here:

`error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found.`

I've double clicked natlink.vcxproj and started the build. In `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\` I only find a file fxcop.xml` and `Microsoft.CodeAnalysis.props`, not `Microsoft.Cpp.Default.props' .... 

Did I miss something when installing the Community version of VS2019 ??  Also, the readme.md refers to *both* 2019 and 2022 versions of VS!

**Comment by dougransom** [comment]
@LexiconCode , I can't remember if was using VS 2021 or VS 2019, and I haven't tried to compile natlink since august.  I think out of desperation i upgraded to 2021 trying to solve an issue (which it didn't)  I don't think that should be required.  Can you look at this please and adjust the docs as necessary?

**Comment by fusentasticus** [comment]
I managed to compile with 2019 -- the problem was that the guided easy download of VS for C++ wasn't complete. The fix is to use the Visual Studio installer tool. (Thanks to @LexiconCode for help.) 

Also, I wrote a task file for VS Code for an alternative IDE.  I have produced a working .pyd file for Dragon 14, compiling from VS Code. 

Plz find enclosed in my PR just submitted.

**Comment by dougransom** [comment]
Y'all can switch to VS Code if that is better for the project. Is there a command line build possible?
