### ISSUE TITLE
Registration Enhancement  - COM Registration could tweak dragon ini files 

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#68]
there is configuration done in natlinkconfig_cli that tweaks dragon naturually speaking ini files.  The CLSID for natlink is added into one of those ini files, and that is how dragon knows to launch natlink through cocreateinstance (create the natlink object).

I think this would be one in DllInstall in natlinkc.pp.

**Comment by quintijn** [comment]
Doug, I don't see what your proposal for enhancement is. Now, via the Dragon ini file Natlink can be included or excluded from running, which is exactly what we want, IMO...

**Comment by dougransom** [comment]
IMO it would be a good idea to have the registration in the ini file done as part of the COM registration process (regsvr32) - this might make things easier to install as we proceed towards making installation easier.  Just an idea.  Maybe it is better the way it is with a script (natlinkconfig_cli).

**Comment by quintijn** [comment]
As far as I understand you, it is done in the natlinkconfig_cli (or natlinkconfig), together with the regsvr32 call. 

For the moment I am in favour of natlinkconfig(_cli) for the com registration as well as for futher configuring things. Via this program anybody can also remove natlink from Dragon again. In the past there were frequent issues that natlink could influence the Dragon recognition process, accuracy, in a negative way. This is not heard for many years now, but still... the possibility of returning Dragon to the situation without Natlink seems good to have.

But, again, maybe I don't understand you...

**Comment by quintijn** [comment]
all done with the inno setup now.

I verified the Dragon inifiles are cleaned up, and the registry keys as well when we Uninstall Natlink (via C:\Program Files (x86)\Natlink\unins000.exe).

Closing this item, OK?
