### ISSUE TITLE
Remove Python Path Requirements

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#69]
It might be possible i remove the requirement for python to be in the system path.  Somehow though the python dll in the correct folder needs to be located. 

A possible solution:

You might be able to use an api https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory  (or others) to control which directories are serached for the DLL, before the DLL is loaded.   The question is when the DLL is loaded?

Another idea:
 - remove the references to the python dll in visual studio and associated headers in the C++ code.
 - for the python dll calls we need, make functions pointers for them in  a header somewhere.
 - use LoadLibrary to get the exact dll we need and getProceAddress to get the functions for the dlll calls we make.  There are only a few that we use from python.h so this should be straightforward.  
 
This might also alleviate the need to recompile for different versions of python (3.8, 3.9, etc)  if that is a requirement now (it may not be, the dll may be compatible with all versions of python).

**Comment by fusentasticus** [comment]
I don't know how to specifically proceed, but here are some general thoughts.

The Python.h header defines PyObject and friends -- essential to compiling the code (there are hundred of references...). 

Usually, the build system would be provided with the location of the python3xx.dll (and other needed object files) -- in CMakeLists file or XML build file.  The build system then bakes it into the manifest that's produced for the object code. 

I don't know this use case, which builds ActiveX/OLE whatever stuff, but it appears that a type library can contain several dll's, including I'd think the python.dll, see  https://docs.microsoft.com/en-us/previous-versions/windows/desktop/automat/contents-of-a-type-library. 

Another reference is https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order 

Currently, it seems as if you're relying on the build system grapping the header and dll locations from Path -- that shouldn't be necessary at all as you've noted. 

BTW, I'm perusing the code; it seems you're were trying to use CMake but reverted to MSBuild instead?

**Comment by dougransom** [comment]
U think we really don't much from python.h.  We just need forward declarations or whatever they are called, since  only pointers are passed around  (i.e. we never have a PyObject to access, just PyObject*).  We use only use a handful of functions, so we can just load those addresses into function pointers and not change any of the code other than loading these addresses at startup.  This really isn't a lot of work.  

The type library is something else.

Changing the  DLL Search order within the COM object could be problematic becuase the Python DLL might already be loaded when natlink.pyd is loaded (because it is linked tot he import library).  I don't  know if DLLs that are loaded by nature of the program being linked to a type library are loaded at startup, or on the first call to a function in that DLL.   

Hence the reason to load the DLL in code rather than by linking a type lib.

**Comment by dougransom** [comment]
Regarding the build, whatever it was doing before about August 2021 wasn't working reliably the project would self destruct and product corrupt output.  I reran the wizard to  create a new ATL project and put all the same code into the new project.  so whatever visual studio set up as  a build is what it does.

**Comment by dougransom** [comment]
Here is another way to solve this and I think the easiest.  There is a[ linker option](https://docs.microsoft.com/en-us/cpp/build/reference/linker-support-for-delay-loaded-dlls?view=msvc-160
) to specify delay loading of DLLs.  Specify that link option, and then use the functions in the earlier comments to change the DLL search path.

**Comment by quintijn** [comment]
I think with the Inno setup process, this issue is not relevant any more. However, the setup process defines some 6 register settings again. I think we do not have to touch these.

**Comment by quintijn** [comment]
This is probably ok now, and even better when the config program (CLI or hopefulli a GUI) is started from a script, that cared for by the installer.
