### ISSUE TITLE
Natlink GUI fails to start using wxpython 4.1.0

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#7]
Python 3.8.2 32-bit
Natlink latest master (as of today's date)
Running from administrator powershell 

Screenshot
![image](https://user-images.githubusercontent.com/24551569/81861367-bde21a00-952d-11ea-8176-eeece12de19d.png)

**Comment by LexiconCode** [comment]
Credit: @dougransom, source Gitter
Workaround is to use wxpython `4.0.7` instead of `4.1.0`
`pip install wxpython==4.0.7`

**Comment by quintijn** [comment]
LexiconCode, did you retry with the suggestion of Doug Ranson? For me it worked.

**Comment by LexiconCode** [comment]
Yes downgrading the dependency works as expected.

**Comment by quintijn** [comment]
I had to downgrade with python 3.7 (64 bits, for my own programming) to wxpython==4.0.3... I expect the same will hold for python 37-32...

When making an installer and these versions for wxpython are taken, the issue should be considered to be solved...
