### ISSUE TITLE
acknowledge ~ and env variables in directories of natlink.ini (natlink-light)

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#79]
I would like that instead of 

UserDirectory = C:\Users\Gebruiker\.natlink\UserDirectory

also: 

UserDirectory = ~\.natlink\UserDirectory or

UserDirectory = %(PERSONALHOME)\.natlink\UserDirectory   (either case sensitive or not, I don't know)

would be recognised. This latter one would solve the problem for more computers, with .natlink directory tied to a onedrive directory, as Doug was asking for.

Also check the directory for validity/existence before loading them, in order to make a better error message, than is now presented:

NatLink: an exception occurred in 'natlink.run_loader'.
Python exception: [WinError 3] The system cannot find the path specified: '~\\.natlink\\UserDirectory'

**Comment by fusentasticus** [comment]
The error message seems perfectly understandable as far as I can see. As for your proposal about environment variables, yes, good idea. Windows defines syntax %APPDATA%, %USERPROFILE%, etc. If you can locate the function in a Windows Python library that'll allow to parse this standard path syntax, then just plug into the code. (Working from Unix is a bad idea I think.) So your request should be doable in two lines: one import and one function call?

**Comment by quintijn** [comment]
I will do this, Quintijn

**Comment by quintijn** [comment]
Working on this. 

1. changed for user conveniece the filename ".natlink" to "natlink.ini"

2. I am going to propose the %PERSONALHOME%   (or %HOMEDRIVE%%HOMEPATH%) and then ".natlink" folder and then "natlink.ini" as the preferable place for the config file.

If people want different, they can either choose setting NATLINK_INI (as is already in the code), needing the complete path of the "natlink.ini" file. 

Or otherwise take up the DICTATIONTOOLBOXHOME offer to have a common folder for all the user definable stuff for Natlink or other DictationToolbox stuff. Inside this folder you then need a ".natlink" folder and the "natlink.ini" file.

3 When the natlink.ini file is not found with these steps, Dragon starts up with the files from InstallTest, which I want to rename into "DefaultConfigFiles". 

Please comment...

**Comment by quintijn** [comment]
I now skipped DICTATIONTOOLBOXHOME, and changed from NATLINK_INI into NATLINK_USERDIR, and must be a directory.
The name of the inifile is now always "natlink.ini".

Moreover the configparser does not like %...% in its entries, so hard coded paths will be needed for the moment.

When using DROPBOX, or ONEDRIVE for synchronising work in user grammars on different computers, these should be configured locally on each computer in the home directory, or for example home/Documents. This second choice is now only made possible when using NATLINK_USERDIR. 

Moreover, when starting natlinkconfigfunctions.py (integration with installer is another issue), the default (fallback) natlink.ini is automatically copied into the home/.natlink or NATLINK_USERDIR/natlink.ini.

Hope this makes sense...
