### ISSUE TITLE
Where can I find the installer?

### ISSUE THREAD

**Issue by joshliberty** [dictation-toolbox/natlink#85]
For the life of me I can't seem to find any up to date installer of Natlink - the README references one but doesn't link to it - as does the natlink website. The only installer I could find was version 4.1 from 2018 – can someone help me out? Thanks!

**Comment by dougransom** [comment]
yeah there was some progress on a python3 version and i think it is super-close to a release.  Check in the gitter you might get some help.

**Comment by quintijn** [comment]
a pre installer version is now at; https://github.com/dictation-toolbox/natlink/releases/tag/natlink5.0.0.pre

Lacking is automatically pip the required packages into the needed python version (python38-32).


(2022-02-07)
