### ISSUE TITLE
inputFromFile function can cause a segfault in some Dragon versions

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/natlink#9]
While looking into https://github.com/daanzu/kaldi-active-grammar/issues/23, I noticed that natlink's `inputFromFile()` function can cause a segmentation fault (i.e. a fatal process crash) in some Dragon versions. It crashes for me in Dragon Home 15, but not in the old version of Dragon 10 I still have. I'm wondering whether this can be fixed in Natlink or if it is a bug with Dragon.

This is the code I was testing with in a separate process to avoid crashing natspeak.exe:
```Python
import natlink

natlink.natConnect()
try:
    natlink.inputFromFile("testing.wav", 0, [], 0)
finally:
    natlink.natDisconnect()

```

The "testing.wav" file is a wave file I recorded with a 16 kHz sample rate, a signed 16-bit (LE) format and one recording channel. The recording contains only a single utterance, so I passed `0` for the `uttDetect` argument.

Interestingly, Dragon will still process the recorded audio if the function is used from a separate process, even if that process crashes.

**Comment by quintijn** [comment]
This is really very very old stuff, and seldom used. I would not know if there is a chance to repair this. Up to Mike or Jan (knork) I think!

**Comment by Danesprite** [comment]
Yes, you're right. This shouldn't have priority over more important changes. Would you like me to submit an update to the natlink.txt file to document the issue?

I do also have a hacky way to workaround the segmentation fault. I will clean it up a bit and post it here in a Python script.

**Comment by quintijn** [comment]
Great, Dane! Yes, please update the natlink.txt file...

**Comment by quintijn** [comment]
Can we close this issue? Or just leave it open, for not forgetting about it...

**Comment by Danesprite** [comment]
Okay then, I will create a pull request tomorrow. I would be fine with closing this issue and labelling it as `wontfix` after updating the function's documentation.

I have completed my workaround script: [natlink_file_input.py](https://gist.github.com/Danesprite/eebacad81af98107ec28d09d9ccf1046). It's working pretty well. Sometimes I need to turn the microphone off before the file's audio is processed, which is not a big deal.
