### ISSUE TITLE
sys.getwindowsversion isn't reporting windows version correctly.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#90]
Edition Windows 11 Pro
Version 21H2
Installed on ‎1/‎29/‎2022
OS build 22000.493
Experience Windows Feature Experience Pack 1000.22000.493.0

`sys.getwindowsversion()`  `sys.getwindowsversion(major=6, minor=2, build=9200, platform=2, service_pack='')`

However running the above code through the interpreter:

> import sys
> sys.getwindowsversion().build
22000

So I'm left scratching my head a little bit on this one. I'm left wondering if Natlink is somehow running Dragon Windows compatibility mode which would default to Windows 8. However I know it's not set that way in executable nor does this happen with any other engine other than Natlink.

An alternative `sys.getwindowsversion().platform_version` which does report windows correctly.

**Comment by fusentasticus** [comment]
I doubt this is bug. Please see https://docs.python.org/3/library/sys.html#sys.getwindowsversion and https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa 
Rather I think that your hunch of a compatibility mode invoked is correct (if the first part of your observations stems from version reporting within natlink)
