### ISSUE TITLE
Install instructions give no indication as to where to find the installer

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#98]

**Comment by quintijn** [comment]
It is found in https://github.com/dictation-toolbox/natlink/releases and I was hoping to have a easier find of this link in the github window.

I also tried to put it in the readme.txt, but when I do this locally and commit and push, in the master branch, I get no change.

I can do it manually in the online github pages, but I would prefer to edit locally.

**Comment by jungar1111** [comment]
@quintijn so I tried to install things a number of different ways including things listed at 

- https://qh.antenna.nl/unimacro/installation/installationexperimentalversionpython3.html ,
- https://test.pypi.org/project/natlinkpy/, https://github.com/dictation-toolbox/natlink/releases, and 
- https://github.com/dictation-toolbox/natlink, and 'no joy' . 

I've some of the cli responses in 

[Install-NatlinkVocolaUnimacroDragonfly-JU20220420-01.txt](https://github.com/dictation-toolbox/natlink/files/8525858/Install-NatlinkVocolaUnimacroDragonfly-JU20220420-01.txt)

Help me fix the install, and I'll write your install docs for you ;) ...

**Comment by quintijn** [comment]
These are now in readme in github home page and in natlink.readthedocs.io
